"""empty message

Revision ID: 893538b5e4a6
Revises: 722e71a49873
Create Date: 2017-08-22 23:47:29.929975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893538b5e4a6'
down_revision = '722e71a49873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_browse', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('body_browse_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_browse_html')
    op.drop_column('posts', 'body_browse')
    # ### end Alembic commands ###
